### PR TITLE
feat: automatically generate declaration files

### PR DESCRIPTION
**Pull request by joshvermaire**
Few things of note:
1. There's a few extra declarations here, like `NamiBridge` and `NamiManager` and other interfaces like `INami`, `INamiCustomerManager`, etc. If these aren't expected we may need make some modifications if they're not wanted to be in the declaration output. 
2. A few others like `ICampaignManager` aren't exported
3. A lot of type declarations were moved to the `types.d.ts` file

### CODE REVIEW

**Review by namidan — COMMENTED** [review]
@joshvermaire doesn't seem like the added declarations are of much consequence, since the publicly facing names seem to alias to them e.g. iNami. Does this seem right to you?

**Comment by joshvermaire** [comment]
I made a script to check the differences between the two, this is what I found:

The `main` branch does not include the following type declarations: [
  'NamiBridge',
  'INami',
  'NamiMLManagerBridge',
  'INamiMLManager',
  'RNNamiCampaignManager',
  'NamiCampaignManagerEvents',
  'ICampaignManager',
  'RNNamiCustomerManager',
  'NamiCustomerManagerEvents',
  'INamiCustomerManager',
  'RNNamiEntitlementManager',
  'NamiEntitlementManagerEvents',
  'INamiEntitlementManager',
  'RNNamiManager',
  'INamiManager',
  'NamiPurchaseManagerBridge',
  'RNNamiPurchaseManager',
  'NamiPurchaseManagerEvents',
  'INamiPurchaseManager',
  'NamiPaywallManagerEvents',
  'ServicesEnum',
  'INamiPaywallManager',
  'NamiSKU',
  'NamiSKUType',
  'AppleProduct',
  'GoogleProduct',
  'AmazonProduct',
  'NamiCampaignRuleType',
  'AccountStateAction'
]

This `update_declaration_files` branch is missing these declarations: [
  'NamiCampaignRule',
  'NamiPaywallEvent',
  'NamiPaywallComponentChange'
]

`NamiCampaignRule` is exported under `NamiCampaignRuleType` which is being used so that seems fine.
`NamiPaywallEvent` is used in [ios/NamiCampaignManagerBridge.swift](https://github.com/namiml/react-native-nami-sdk/blob/74fbc484472b865e9201a455476b8e1a9a7791d2/ios/NamiCampaignManagerBridge.swift#L46) and [android/src/main/java/com/nami/reactlibrary/NamiCampaignManagerBridge.kt](https://github.com/namiml/react-native-nami-sdk/blob/74fbc484472b865e9201a455476b8e1a9a7791d2/android/src/main/java/com/nami/reactlibrary/NamiCampaignManagerBridge.kt#L13). So I will add this declaration back in but it would be good if it could be confirmed that it works properly as I'm not 100% sure how (and if) these two files interact with these types.
`NamiPaywallComponentChange` is not directly used in this repo outside of the `NamiPaywallEvent`.

I'm assuming it's ok if the type declarations that were missing from the main branch are included in new builds, but if we want to formally exclude those we would need to add that.

**Comment by joshvermaire** [comment]
Here's a link to the script if you ever need it: https://gist.github.com/joshvermaire/15ccd0e0e88baaba90daac76be5ccfd5

You can run it via `ts-node compare_declaration_files.ts`

**Comment by joshvermaire** [comment]
> @joshvermaire doesn't seem like the added declarations are of much consequence, since the publicly facing names seem to alias to them e.g. iNami. Does this seem right to you?

Yes, I think that's right. I don't see it as an issue. In the future if you wanted to 'clean things up' we could make some changes to exclude them, but I don't see it causing any issues

**Review by namidan — APPROVED** [review]

**Pull request merged**
